GET http://localhost:5001/social-app-e7b22/us-central1/api/screams HTTP/1.1

###
POST http://localhost:5001/social-app-e7b22/us-central1/api/screams HTTP/1.1
Content-Type: application/json

{
    "body": "From test",
    "userHandle": "new"
}

###
POST http://localhost:5001/social-app-e7b22/us-central1/api/signup HTTP/1.1
Content-Type: application/json

{
    "email": "user@email.com",
    "password": "23REYTHGFDG",
    "confirmPassword": "23REYTHGFDG",
    "handle": "user"
}

###
POST http://localhost:5001/social-app-e7b22/us-central1/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "user@email.com",
    "password": "23REYTHGFDG"
}
###