GET https://us-central1-social-app-e7b22.cloudfunctions.net/api/screams HTTP/1.1

###
POST https://us-central1-social-app-e7b22.cloudfunctions.net/api/screams HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImZjMmM4YmIyNmE3OGM0M2JkODYzNzA1YjNkNzkyMWI0ZTY0MjVkNTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsLWFwcC1lN2IyMiIsImF1ZCI6InNvY2lhbC1hcHAtZTdiMjIiLCJhdXRoX3RpbWUiOjE1ODkwMzQxMDEsInVzZXJfaWQiOiJoVTZpZzNvNDlKZW4yZk1RSUIwZWhJalNkM2gyIiwic3ViIjoiaFU2aWczbzQ5SmVuMmZNUUlCMGVoSWpTZDNoMiIsImlhdCI6MTU4OTAzNDEwMSwiZXhwIjoxNTg5MDM3NzAxLCJlbWFpbCI6Im1heWtvbkBlbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsibWF5a29uQGVtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.XezVaWC9qAeD3g9UNAvQhhrdZX2HBoIk6yYip9z7cuTcTf1Nc4PosvgZUm6JKGdIlsIQvQ6sYnCh_r6brSFxEt-s28skPqg-CVeSk-Q3m_2M1vIgWLqIcud23H_Zg1ZpbdXJ1A8RsC0yj3pW7Fe7KfK93x1wTdXJSwZ6-5lT-I_4ZZDnzExqxQhxlGBA6lwbrRtgEGCGNkSE_m5RCzFgL8wDYOXkkFF_PhAxdLvWUwy78-NKRWT-eGQjmmKEMMDepP_5qKQlzYwHmBboR7KyGEP6VMhVleVK4GoLTqt4i6k0io6yfpqgts1HukxeSwOxOh0kBAkvJs8CUreOaTWTUw

{
    "body": "A great scream 07"
}

###
POST https://us-central1-social-app-e7b22.cloudfunctions.net/api/signup HTTP/1.1
Content-Type: application/json

{
    "email": "jake@email.com",
    "password": "23REYTHGFDG",
    "confirmPassword": "23REYTHGFDG",
    "handle": "jake"
}

###
POST https://us-central1-social-app-e7b22.cloudfunctions.net/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "jake@email.com",
    "password": "23REYTHGFDG"
}
###